# Generated by Django 4.0.4 on 2022-05-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_snack_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='description',
            field=models.TextField(),
        ),
    ]
